# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('url_OFF', models.CharField(max_length=1024)),
                ('product_name', models.CharField(db_index=True, max_length=512)),
                ('generic_name', models.CharField(db_index=True, max_length=1024)),
                ('quantity', models.CharField(blank=True, max_length=512)),
                ('packaging', models.CharField(blank=True, max_length=512)),
                ('packaging_tags', models.CharField(blank=True, max_length=512)),
                ('brands', models.CharField(blank=True, max_length=512)),
                ('brands_tags', models.CharField(blank=True, max_length=512)),
                ('categories', models.CharField(blank=True, max_length=1024)),
                ('categories_tags', models.CharField(blank=True, max_length=1024)),
                ('categories_fr', models.CharField(blank=True, max_length=1024)),
                ('labels', models.CharField(blank=True, max_length=1024)),
                ('labels_tags', models.CharField(blank=True, max_length=1024)),
                ('labels_fr', models.CharField(blank=True, max_length=1024)),
                ('purchase_places', models.CharField(blank=True, max_length=256)),
                ('image_url', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
