# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:54
from __future__ import unicode_literals

from django.db import migrations, models
from utils.images import set_measure_thumbnail


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    measures = apps.get_model("weights", "Measure")
    db_alias = schema_editor.connection.alias
    for measure in measures.objects.using(db_alias).all():
        set_measure_thumbnail(measure)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
