# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0003_pigeonuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pigeonuser',
            old_name='achivements',
            new_name='achievements',
        ),
    ]
