# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright © 2017 Benoît Latinier, Fabien Bourrel
#  This file is part of project: OnEstPasDesPigeons
#
# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import weights.models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0004_auto_20170718_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_weight', models.IntegerField()),
                ('measured_weight', models.IntegerField()),
                ('measure_image', models.ImageField(blank=True, null=True, upload_to=weights.models.get_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weights.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weights.PigeonUser')),
            ],
        ),
    ]
