# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0006_auto_20170728_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
