# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0007_measure_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
