# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0008_auto_20170817_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
