# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0009_auto_20170820_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(default='OpenFoodFacts', max_length=32),
        ),
    ]
