# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0010_product_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('oz', 'oz')], default='g', max_length=6),
        ),
    ]
