'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var LOGIN_USER_REQUEST = exports.LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
var LOGIN_USER_SUCCESS = exports.LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
var LOGIN_USER_FAILURE = exports.LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

var LOGOUT_USER = exports.LOGOUT_USER = 'LOGOUT_USER';

var REGISTER_USER_REQUEST = exports.REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
var REGISTER_USER_SUCCESS = exports.REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
var REGISTER_USER_FAILURE = exports.REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';